{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "webhook-demo.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "webhook-demo.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{ include "webhook-demo.serviceAccountName" . }}-reader"
rules:
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - create
  - get 
  - list
{{- end }}
---
{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{ include "webhook-demo.serviceAccountName" . }}-reader"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{ include "webhook-demo.serviceAccountName" . }}-reader"
subjects:
- kind: ServiceAccount
  name: {{ include "webhook-demo.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}